---
dataset:
  train:
    root: "hw2_data/p2_data/train"
  valid:
    root: "hw2_data/p2_data/validation"

loader:
  batch_size: 32
  num_workers: 4

# Adam optimzier
optim:
  lr: 0.0001

train:
  agent: "SegmentAgent"
  model: "fcn"
  exp_name: "fcn32_segmentation"
  log_dir: "run"
  checkpoint_dir: "fcn32_checkpoint"
  device: "cuda"
  n_epochs: 50
  interval: 10
  resume: false
